name: a_3_salon
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.2
  font_awesome_flutter: ^10.3.0
  icons_plus: ^5.0.0
  url_launcher: ^6.0.20
  google_fonts: ^4.0.3
  image_picker: ^0.8.4+8
  intl: ^0.17.0
  shake_gesture: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  qr_flutter: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
