name: a_3_salon
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.2
  font_awesome_flutter: ^10.5.0
  icons_plus: ^5.0.0
  url_launcher: ^6.1.8
  google_fonts: ^4.0.3
  image_picker: ^0.8.4+8
  pdf: ^3.6.0
  permission_handler: ^11.3.1
  intl: ^0.17.0
  shake_gesture: ^1.0.8
  cupertino_icons: ^1.0.8
  screenshot: ^3.0.0
  share_plus: ^10.1.2
  path_provider: ^2.1.5
  shared_preferences: ^2.0.18
  printing: ^5.6.0
  responsive_sizer: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  qr_flutter: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/